import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const sourcePath = resolve(root, 'src', 'extension-host.cjs');
const apiSourcePath = resolve(root, 'src', 'vscode-api.cjs');
const loaderSourcePath = resolve(root, 'src', 'extension-loader.cjs');
const outputPath = resolve(root, 'dist', 'extension-host.js');
const source = await readFile(sourcePath, 'utf8');
const apiSource = await readFile(apiSourcePath, 'utf8');
const loaderSource = await readFile(loaderSourcePath, 'utf8');

const bundledImports = new Set(['./vscode-api.cjs', './extension-loader.cjs']);
const forbiddenImports = [...`${source}\n${apiSource}\n${loaderSource}`.matchAll(/require\(['"]([^'"]+)['"]\)/g)]
  .map((match) => match[1])
  .filter((specifier) => !specifier.startsWith('node:') && !bundledImports.has(specifier));
if (forbiddenImports.length !== 0) {
  throw new Error(`The extension host bundle has external imports: ${forbiddenImports.join(', ')}`);
}

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by src/exthost/build.mjs. Do not edit.\n` +
    `'use strict';\n` +
    `const __sakura_modules = Object.create(null);\n` +
    `const __sakura_cache = Object.create(null);\n` +
    `function __sakura_require(id) {\n` +
    `  if (__sakura_cache[id]) return __sakura_cache[id].exports;\n` +
    `  const factory = __sakura_modules[id];\n` +
    `  if (!factory) return require(id);\n` +
    `  const localModule = { exports: {} };\n` +
    `  __sakura_cache[id] = localModule;\n` +
    `  factory(localModule, localModule.exports, __sakura_require);\n` +
    `  return localModule.exports;\n` +
    `}\n` +
    `__sakura_require.resolve = require.resolve;\n` +
    `__sakura_modules['./vscode-api.cjs'] = function(module, exports, require) {\n${apiSource}\n};\n` +
    `__sakura_modules['./extension-loader.cjs'] = function(module, exports, require) {\n${loaderSource}\n};\n` +
    `__sakura_modules['entry'] = function(module, exports, require) {\n${source}\n};\n` +
    `const __sakura_entry = __sakura_require('entry');\n` +
    `if (require.main === module) {\n` +
    `  __sakura_entry.runMain().catch((error) => { console.error(error); process.exitCode = 1; });\n` +
    `}\n`,
  'utf8',
);
console.log(`Built ${outputPath}`);
