name: Doxygen

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  doxygen:
    runs-on: windows-latest
    strategy:
      matrix:
        BuildPlatform: [x64]
        Configuration: [Release]
    env:
      BuildPlatform: ${{ matrix.BuildPlatform }}
      Configuration: ${{ matrix.Configuration }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            doxygen

      - name: Show environment variables for debug
        run: set
        shell: cmd

      - name: Run doxygen
        run: ./run-doxygen.bat ${{ env.BuildPlatform }} ${{ env.Configuration }}
        shell: msys2 {0}

      - name: Upload doxygen artifact
        uses: actions/upload-artifact@v7
        with:
          name: doxygen_${{ env.BuildPlatform }}_${{ env.Configuration }}
          path: |
            html
            doxygen-${{ env.BuildPlatform }}-${{ env.Configuration }}.log
          if-no-files-found: error
